<?php 
$config['per_page']              = 2;
$config['prefix']                = '';
$config['suffix']                = '';
$config['total_rows']            = 0;
$config['num_links']             = 2;
$config['cur_page']              = 0;
$config['use_page_numbers']      = TRUE;
$config['first_link']            = '<< First';
$config['next_link']             = '&gt;';
$config['prev_link']             = '&lt;';
$config['last_link']             = 'Last >>';
$config['uri_segment']           = 0;
$config['full_tag_open']         = '<ul class="pagination pagination-separated m-15">';
$config['full_tag_close']        = '</ul>';
$config['first_tag_open']        = '<li>';
$config['first_tag_close']       = '</li>';
$config['last_tag_open']         = '<li>';
$config['last_tag_close']        = '</li>';
$config['first_url']             = '';
$config['cur_tag_open']          = '<li class="active"><a class="" href="#">';
$config['cur_tag_close']         = '</a></li>';
$config['next_tag_open']         = '<li>';
$config['next_tag_close']        = '</li>';
$config['prev_tag_open']         = '<li>';
$config['prev_tag_close']        = '</li>';
$config['num_tag_open']          = '<li>';
$config['num_tag_close']         = '</li>';
$config['page_query_string']     = TRUE;
$config['query_string_segment']  = 'page';
$config['display_pages']         = TRUE;
$config['_attributes']           = '';
$config['_link_types']           = array();
$config['reuse_query_string']    = FALSE;
$config['use_global_url_suffix'] = FALSE; 
?>